# Use the official PostgreSQL image as a parent image
FROM postgres:latest

EXPOSE 5432

# Set environment variables
ENV POSTGRES_DB postgres \
    POSTGRES_USER postgres \
    POSTGRES_PASSWORD password
